### ISSUE TITLE
パッケージの名前をわかりやすくする

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/cit_adis_imu#14]
過去の資産から流用した結果、非常に分かりづらいパッケージ名「imu」となっているためアナデバ製であることが分かるように修正する。

https://github.com/open-rdc/adis_imu_drivers/issues/13 でリリースする前に行う

**Comment by DaikiMaekawa** [comment]
@Nasupl このタスクをお願いしてもよろしいですか? 手が回らなければ大会後でも構いません。

**Comment by Nasupl** [comment]
@DaikiMaekawa 
本走行後に着手します

**Comment by DaikiMaekawa** [comment]
ありがとう。 ROSのパッケージ名は被るとビルド出来なくなるため、製品名等を付けてユニークなものにするのが一般的です。

**Comment by DaikiMaekawa** [comment]
この件は気が向いた時に私がやっておきますよ。 我々の独自基盤専用のインタフェースなのでcit_xxxのプレフィックスを付けることを検討しています。 私もこのパッケージをリリースしたところで第三者の需要が無いことは重々承知していますが、これをdebリリースしないとorne_navigationをリリース出来ないというジレンマがあります。

**Comment by DaikiMaekawa** [comment]
cit_adis_imuへと変更した。 変更前のソースを使用したい場合は0.0.1タグに切り替えること。
